apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-airflowdev-dags
  namespace: k8s-tasks
  labels:
    usuage: k8s-airflowdev-dags
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  storageClassName: airflow-sc
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: airflow-dags
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000

