apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: airflow-sc
  volumeName: airflow-dags
